version: '3.7'
services:
    app:
        build: .
        ports:
            - 5002:3000
        depends_on:
            - "mysql"
        environment:
            - NODE_ENV=${NODE_ENV}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    mysql:
        build:
            context: ./data
            args:
                - NODE_ENV=${NODE_ENV}
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: always
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}