# TODO CREAR NETWORK
version: '3.7'
networks:
    ntk-app:
        driver: bridge
        name: ntk-app
services:
    nginx-liburutegia:
        container_name: nginx-liburutegia
        image: nginx:latest
        restart: always
        ports: 
            - ${NGINX_PORT}:${NGINX_PORT}
        depends_on:
            - app-liburutegia
        volumes:
            - ./containers/nginx-liburutegia/templates:/etc/nginx/templates
        environment:
            - PORT=${PORT}
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_PORT=${NGINX_PORT}
            - NGINX_APP=${NGINX_APP}
            - APP1_PORT=${APP1_PORT}
            - APP2_PORT=${APP2_PORT}
        networks:
            - ntk-app
    app-liburutegia:
        container_name: app-liburutegia
        build: .
        ports:
            - ${APP1_PORT}:${PORT}
        depends_on:
            - "mysql-liburutegia"
            - "minio-liburutegia"
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - MINIO_BUCKET=${MINIO_BUCKET}
            - MINIO_HOST=${MINIO_HOST}
            - MINIO_PORT=${MINIO_PORT}
            - MINIO_USER=${MINIO_USER}
            - MINIO_PASSWORD=${MINIO_PASSWORD}
        volumes:
            - ./src:/app/src
        networks:
          - ntk-app
    redis-liburutegia:
      container_name: redis-liburutegia
      image: redis
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ~/Application/redis:/usr/local/etc/redis/:ro
      cap_add:
        - SYS_PTRACE
      command: redis-server /usr/local/etc/redis/redis.conf
      environment:
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      networks:
        - ntk-app
    redis-commander:
      container_name: redis-commander
      image: rediscommander/redis-commander
      ports:
        - "8081:8081"
      environment:
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_DB_INDEX=0
      volumes:
        - redis-commander-config:/usr/local/lib/node_modules/redis-commander/config:rw
      networks:
        - ntk-app
    mysql-liburutegia:
        container_name: mysql-liburutegia
        build:
          context: ./containers/mysql
        restart: always
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ~/Application/mysql-data:/var/lib/mysql
        networks:
            - ntk-app
    minio-liburutegia:
      container_name: minio-liburutegia
      image: quay.io/minio/minio:latest
      ports: 
          - 9000:9000
          - 9090:9090
      environment:
          - MINIO_HOST=${MINIO_HOST}
          - MINIO_ROOT_USER=${MINIO_USER}
          - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      volumes:
            - ~/Application/minio/data:/data
      command: ["server", "/data", "--console-address", ":9090"]
      networks:
          - ntk-app
volumes:
  redis-commander-config: