# TODO CREAR NETWORK
version: '3.7'
networks:
    ntk-app:
        driver: bridge
        name: ntk-app
services:
    liburutegia-nginx:
        container_name: liburutegia-nginx
        image: nginx:latest
        restart: always
        ports: 
            - ${NGINX_PORT}:${NGINX_PORT}
        depends_on:
            - application
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        environment:
            - PORT=${PORT}
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_PORT=${NGINX_PORT}
            - NGINX_APP=${NGINX_APP}
        networks:
            - ntk-app
    application:
        container_name: application
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - "mysql"
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_HOST=${REDIS_HOST}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./src:/app/src
            - ./src/public/img/covers:/app/src/public/img/covers
        networks:
            - ntk-app
    redis-liburutegia:
      container_name: redis-liburutegia
      image: redis
      ports: 
          - ${REDIS_PORT}:6379
      networks:
          - ntk-app
    mysql:
        container_name: mysql
        build:
          context: ./containers/mysql
        restart: always
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            ntk-app:
              aliases:
                - "mysql"