version: '3.7'
networks:
  ntk-app:
    driver: bridge
    name: ntk-app
services:
    redis-liburutegia:
      container_name: redis-liburutegia
      image: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - "~/dev/docker/containers/redis:/usr/local/etc/redis/:ro"
      command: redis-server /usr/local/etc/redis/redis.conf
      environment:
          REDIS_PASSWORD: Dopracau4000lopo
      networks:
        - ntk-app
    redis-commander:
      container_name: redis-commander
      image: rediscommander/redis-commander
      restart: always
      ports:
          - "8082:8081"
      environment:
          REDIS_HOST: redis-liburutegia
          REDIS_PASSWORD: Dopracau4000lopo
          REDIS_DB_INDEX: 0
      volumes:
        - redis-commander-config:/usr/local/lib/node_modules/redis-commander/config:rw
      networks:
        - ntk-app
    mysql-liburutegia:
        container_name: mysql-liburutegia
        image: lopuma/db-liburutegia:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: liburutegia
            MYSQL_PASSWORD: Dopracau4000lopo
            MYSQL_ROOT_PASSWORD: Dopracau4000lopo
        volumes:
            - "~/dev/docker/containers/database/mysql/db-liburutegia:/var/lib/mysql"
        networks:
            - ntk-app
    minio-liburutegia:
      container_name: minio-liburutegia
      image: minio/minio:latest
      restart: always
      ports: 
          - "9000:9000"
          - "9001:9001"
      environment:
            MINIO_ROOT_USER: lopuma
            MINIO_ROOT_PASSWORD: Dopracau4000lopo
      volumes:
            - "~/dev/docker/containers/minio/data-liburutegia:/data"
      command: ["server", "/data", "--console-address", ":9001"]
      networks:
          - ntk-app
volumes:
  redis-commander-config: