version: '3.7'
networks:
    ntk-app:
        driver: bridge
        name: ntk-app
services:
    nginx-liburutegia:
        container_name: nginx-liburutegia
        image: nginx:latest
        restart: always
        ports: 
            - "${NGINX_PORT}:${NGINX_PORT}"
        depends_on:
            - app-liburutegia
        volumes:
            - ./containers/nginx-liburutegia/templates:/etc/nginx/templates
        environment:
              PORT: ${PORT}
              NGINX_HOST: ${NGINX_HOST}
              NGINX_PORT: ${NGINX_PORT}
              NGINX_APP: ${NGINX_APP}
        networks:
            - ntk-app
    app-liburutegia:
        container_name: app-liburutegia
        build: .
        restart: always
        ports:
            - "${PORT}:${PORT}"
        environment:
              MYSQL_HOST: mysql-liburutegia
              REDIS_HOST: redis-liburutegia
              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
              MYSQL_DATABASE: ${MYSQL_DATABASE}
              REDIS_PASSWORD: ${REDIS_PASSWORD}
              MINIO_HOST: "${MINIO_HOST}"
              BUCKET_NAME: ${BUCKET_NAME}
              MINIO_USER: ${MINIO_USER}
              MINIO_PASSWORD: ${MINIO_PASSWORD}
        volumes:
            - ./src:/app/src
        networks:
          - ntk-app
    redis-liburutegia:
      container_name: redis-liburutegia
      image: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ~/Volumenes/redis:/usr/local/etc/redis/:ro
      command: redis-server /usr/local/etc/redis/redis.conf
      environment:
          REDIS_PASSWORD: ${REDIS_PASSWORD}
      networks:
        - ntk-app
    redis-commander:
      container_name: redis-commander
      image: rediscommander/redis-commander
      restart: always
      ports:
          - "8081:8081"
      environment:
          REDIS_HOST: redis-liburutegia
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_DB_INDEX: 0
      volumes:
        - redis-commander-config:/usr/local/lib/node_modules/redis-commander/config:rw
      networks:
        - ntk-app
    mysql-liburutegia:
        container_name: mysql-liburutegia
        build:
          context: ./containers/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ~/Volumenes/mysql-data:/var/lib/mysql
        networks:
            - ntk-app
    minio-liburutegia:
      container_name: minio-liburutegia
      image: minio/minio:latest
      restart: always
      ports: 
          - "9000:9000"
          - "9001:9001"
      environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      volumes:
            - ~/Volumenes/minio/data:/data
      command: ["server", "/data", "--console-address", ":9001"]
      networks:
          - ntk-app
volumes:
  redis-commander-config: